#

heat_template_version: 2013-05-23

description: Rackspace Axios Demo

parameters:
  contract_id:
    label: Contract ID
    description: Unique Contract ID
    type: string

  post_init_notification_url:
    label: Post-initialisation Notification URL
    description: URL to post to once a server has initialised
    type: string

  ssh_keypair_name:
    label: SSH Key Pair
    description: Name of an existing key pair to use for all servers
    type: string
    default: ""

resources:
  load_balancer:
    type: "Rackspace::Cloud::LoadBalancer"
    properties:
      name:
        str_replace:
          template: '%name%-lb'
          params:
            '%name%': { get_param: "OS::stack_name" }
      nodes: []
      healthMonitor:
        type: CONNECT
        delay: 10
        timeout: 2
        attemptsBeforeDeactivation: 2
      port: 80
      protocol: HTTP
      algorithm: ROUND_ROBIN
      contentCaching: DISABLED
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      metadata:
        parent_stack_id: { get_param: "OS::stack_id" }
        group_name: { get_param: "OS::stack_name" }
        contract_id: { get_param: contract_id }
        environment: "test"

  asg:
    type: Rackspace::AutoScale::Group
    properties:
      groupConfiguration:
        name:
          str_replace:
            template: '%name%-asg'
            params:
              '%name%': { get_param: "OS::stack_name" }
        cooldown: 60
        minEntities: 1
        maxEntities: 16
        metadata:
          parent_stack_id: { get_param: "OS::stack_id" }
          group_name: { get_param: "OS::stack_name" }
          contract_id: { get_param: contract_id }
          environment: "test"
      launchConfiguration:
        type: launch_server
        args:
          loadBalancers:
            -
              loadBalancerId: { get_resource: load_balancer }
              port: 80
          server:
            name:
              str_replace:
                template: '%name%'
                params:
                  '%name%': { get_param: "OS::stack_name" }
            # WARNING: Hardcoded flavor and image below!
            flavorRef: 3
            imageRef: 09de0a66-3156-48b4-90a5-1cf25a905207
            key_name: { get_param: ssh_keypair_name }
            diskConfig: MANUAL
            user_data:
              str_replace:
                template: |
                  #cloud-config
                  package_update: true
                  packages:
                    - curl

                  output : { all : '| tee -a /var/log/cloud-init-output.log' }

                  write_files:
                    #  Bootstrap script
                    - path: /tmp/heat-bootstrap.sh
                      permissions: '0500'
                      content: |
                        #!/bin/bash -ex

                        # Get public IP address (from a reputable source)
                        PUBLIC_IP=$(curl http://checkip.amazonaws.com)

                        # Send a notification to our URL
                        curl -vv "$post_init_notification_url&NODE_IP=${PUBLIC_IP}&CONTRACT_ID=$contract_id&NODE_NAME=$(hostname)"
                  runcmd:
                    - /tmp/heat-bootstrap.sh
                params:
                  #wc_notify: { get_attr: ['wait_condition_handle', 'curl_cli'] }
                  $group_name: { get_param: "OS::stack_name" }
                  $post_init_notification_url: { get_param: post_init_notification_url }
                  $contract_id: { get_param: contract_id }
            networks:
              - uuid: 11111111-1111-1111-1111-111111111111
              - uuid: 00000000-0000-0000-0000-000000000000
            metadata:
              parent_stack_id: { get_param: "OS::stack_id" }
              group_name: { get_param: "OS::stack_name" }
              contract_id: { get_param: contract_id }
              environment: "test"
              role: "web"

  # Scaling policies and webhooks
  scale-to-00:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-to-00
      desiredCapacity: 0
      cooldown: 59
      type: webhook

  scale-to-00-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-to-00}
      name: scale-to-00-webhook

  scale-to-01:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-to-01
      desiredCapacity: 1
      cooldown: 59
      type: webhook

  scale-to-01-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-to-01}
      name: scale-to-01-webhook

  scale-to-02:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-to-02
      desiredCapacity: 2
      cooldown: 59
      type: webhook

  scale-to-02-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-to-02}
      name: scale-to-02-webhook

  scale-to-04:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-to-04
      desiredCapacity: 4
      cooldown: 59
      type: webhook

  scale-to-04-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-to-04}
      name: scale-to-04-webhook

  scale-to-08:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-to-08
      desiredCapacity: 8
      cooldown: 59
      type: webhook

  scale-to-08-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-to-08}
      name: scale-to-08-webhook

  scale-up-01:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-up-01
      change: 1
      cooldown: 59
      type: webhook

  scale-up-01-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-up-01}
      name: scale-up-01-webhook

  scale-up-25pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-up-25pc
      changePercent: 25
      cooldown: 59
      type: webhook

  scale-up-25pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-up-25pc}
      name: scale-up-25pc-webhook

  scale-up-50pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-up-50pc
      changePercent: 50
      cooldown: 59
      type: webhook

  scale-up-50pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-up-50pc}
      name: scale-up-50pc-webhook

  scale-up-75pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-up-75pc
      changePercent: 75
      cooldown: 59
      type: webhook

  scale-up-75pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-up-75pc}
      name: scale-up-75pc-webhook

  scale-up-100pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-up-100pc
      changePercent: 100
      cooldown: 59
      type: webhook

  scale-up-100pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-up-100pc}
      name: scale-up-100pc-webhook

  scale-up-200pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-up-200pc
      changePercent: 200
      cooldown: 59
      type: webhook

  scale-up-200pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-up-200pc}
      name: scale-up-200pc-webhook

  scale-up-300pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-up-300pc
      changePercent: 300
      cooldown: 59
      type: webhook

  scale-up-300pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-up-300pc}
      name: scale-up-300pc-webhook

  scale-down-01:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-down-01
      change: -1
      cooldown: 59
      type: webhook

  scale-down-01-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-down-01}
      name: scale-down-01-webhook

  scale-down-25pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-down-25pc
      changePercent: -25
      cooldown: 59
      type: webhook

  scale-down-25pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-down-25pc}
      name: scale-down-25pc-webhook

  scale-down-50pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-down-50pc
      changePercent: -50
      cooldown: 59
      type: webhook

  scale-down-50pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-down-50pc}
      name: scale-down-50pc-webhook

  scale-down-75pc:
    type: Rackspace::AutoScale::ScalingPolicy
    properties:
      group: {get_resource: asg}
      name: scale-down-75pc
      changePercent: -75
      cooldown: 59
      type: webhook

  scale-down-75pc-webhook:
    type: Rackspace::AutoScale::WebHook
    properties:
      policy: {get_resource: scale-down-75pc}
      name: scale-down-75pc-webhook

outputs:
  lb_public_ip:
    description: Public IP of the load balancer
    value: {get_attr: [load_balancer, PublicIp]}
  scale-to-00-webhook:
    description: Webhook - scale to zero
    value: {get_attr: [scale-to-00-webhook, capabilityUrl]}
  scale-to-01-webhook:
    description: Webhook - scale to one
    value: {get_attr: [scale-to-01-webhook, capabilityUrl]}
  scale-to-02-webhook:
    description: Webhook - scale to two
    value: {get_attr: [scale-to-02-webhook, capabilityUrl]}
  scale-to-04-webhook:
    description: Webhook - scale to four
    value: {get_attr: [scale-to-04-webhook, capabilityUrl]}
  scale-to-08-webhook:
    description: Webhook - scale to eight
    value: {get_attr: [scale-to-08-webhook, capabilityUrl]}
  scale-up-01-webhook:
    description: Webhook - scale up 1
    value: {get_attr: [scale-up-01-webhook, capabilityUrl]}
  scale-down-01-webhook:
    description: Webhook - scale down 1
    value: {get_attr: [scale-down-01-webhook, capabilityUrl]}
  scale-up-25pc-webhook:
    description: Webhook - scale up 25 percent
    value: {get_attr: [scale-up-25pc-webhook, capabilityUrl]}
  scale-down-25pc-webhook:
    description: Webhook - scale down 25 percent
    value: {get_attr: [scale-down-25pc-webhook, capabilityUrl]}
  scale-up-50pc-webhook:
    description: Webhook - scale up 50 percent
    value: {get_attr: [scale-up-50pc-webhook, capabilityUrl]}
  scale-down-50pc-webhook:
    description: Webhook - scale down 50 percent
    value: {get_attr: [scale-down-50pc-webhook, capabilityUrl]}
  scale-up-75pc-webhook:
    description: Webhook - scale up 75 percent
    value: {get_attr: [scale-up-75pc-webhook, capabilityUrl]}
  scale-down-75pc-webhook:
    description: Webhook - scale down 75 percent
    value: {get_attr: [scale-down-75pc-webhook, capabilityUrl]}
  scale-up-100pc-webhook:
    description: Webhook - scale up 100 percent
    value: {get_attr: [scale-up-100pc-webhook, capabilityUrl]}
  scale-up-200pc-webhook:
    description: Webhook - scale up 200 percent
    value: {get_attr: [scale-up-200pc-webhook, capabilityUrl]}
  scale-up-300pc-webhook:
    description: Webhook - scale up 300 percent
    value: {get_attr: [scale-up-300pc-webhook, capabilityUrl]}